# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-26 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 12, 26, 7, 44, 4, 488867, tzinfo=utc)),
        ),
    ]
