# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-22 06:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must contains ". @ + -"', regex='^[a-zA-Z0-9.@+-]*$')]),
        ),
    ]
