# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-26 04:05
from __future__ import unicode_literals

import cars.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(null=True, related_name='drivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=models.SET(cars.models.set_delete_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='first_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
