# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-26 04:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_auto_20171226_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='update_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='drivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
