# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171213_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author_email',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
