# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-14 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171213_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='', error_messages={'blank': 'this title is blank, please try again!', 'unique': 'this title is not unique, please try again!'}, help_text='must be an unique title', max_length=20, unique=True),
        ),
    ]
