# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-14 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171214_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModelManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
